name: Update Players Stats

on: workflow_dispatch
  # schedule:
  #   - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Instabul"

      - name: Checkout Repository Content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
         path: "requirements.txt"

      - name: Execute Python Script
        run: python updatePlayerStats.py

      - name: Check For Any Change
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit Changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.name carletch 
          git config --local user.email "carletch.office@gmail.com"
          git add --all 
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main 
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}} 
          username: github-actions
          
